services:
  - type: web
    name: loader-admin
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true 